# Generated by Django 3.2.4 on 2021-06-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Choice',
        ),
    ]
