# Generated by Django 3.2.4 on 2021-06-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.CharField(default='none', max_length=120),
            preserve_default=False,
        ),
    ]
